-- schema.sql
-- This file defines the database structure for the Gem Origin Tracking System.
-- SQLite is used because it requires no separate server installation,
-- making it lightweight and suitable for a desktop Java application.
-- All tables are created only if they do not already exist,
-- so this file can be run multiple times without errors.


-- ---------------------------------------------------------
-- Table: gems
-- ---------------------------------------------------------
-- This table stores the top-level information about each gem.
-- Each gem gets one row here, identified by a unique gem_id.
-- The detailed stage-by-stage journey is stored in gem_stages table.
-- Separating gem info from stage info avoids repeating gem type
-- and origin data in every single stage row.
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS gems (
    gem_id              TEXT PRIMARY KEY,       -- Unique ID for each gem, e.g. GEM-001
    gem_type            TEXT NOT NULL,          -- e.g. Blue Sapphire, Ruby, Cat's Eye
    color_description   TEXT,                   -- Hue, tone and saturation details
    original_weight     REAL NOT NULL,          -- Weight in carats at time of mining
    origin_mine         TEXT NOT NULL,          -- Name of the mine where gem was found
    origin_district     TEXT NOT NULL,          -- District of the mine e.g. Ratnapura
    origin_village      TEXT,                   -- Village near the mine if known
    mining_date         TEXT NOT NULL,          -- Date of extraction in YYYY-MM-DD format
    is_ceylon_gem       INTEGER DEFAULT 1,      -- 1 = verified Ceylon gem, 0 = not verified
    qr_code_path        TEXT,                   -- File path to the generated QR code image
    created_at          TEXT DEFAULT (datetime('now'))  -- Timestamp when record was created
);


-- ---------------------------------------------------------
-- Table: gem_stages
-- ---------------------------------------------------------
-- This table stores each individual stage in a gem's journey.
-- Each row represents one node in the doubly linked list.
-- The stage_order column is used to reconstruct the linked list
-- in the correct sequence when loading data from the database.
-- Without stage_order, we would not know which node comes first.
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS gem_stages (
    stage_id            INTEGER PRIMARY KEY AUTOINCREMENT,  -- Auto-generated unique row ID
    gem_id              TEXT NOT NULL,                      -- Foreign key linking to gems table
    stage_type          TEXT NOT NULL,                      -- MINING, CUTTING, TRADING, EXPORTING, BUYING
    stage_order         INTEGER NOT NULL,                   -- Position in the chain, starts at 1
    location            TEXT NOT NULL,                      -- Where this stage took place
    person_name         TEXT NOT NULL,                      -- Name of person responsible at this stage
    person_id_number    TEXT,                               -- NIC or passport number of the person
    contact_number      TEXT,                               -- Contact number of the person
    weight_in_carats    REAL NOT NULL,                      -- Gem weight at this stage
    price_in_rupees     REAL NOT NULL,                      -- Gem value at this stage in LKR
    stage_date          TEXT NOT NULL,                      -- Date of this stage in YYYY-MM-DD format
    certificate_number  TEXT,                               -- Certificate number if issued at this stage
    issuing_authority   TEXT,                               -- Name of the certificate issuing body
    flight_number       TEXT,                               -- Flight number, only for EXPORTING stage
    invoice_number      TEXT,                               -- Invoice number, only for EXPORTING stage
    destination_country TEXT,                               -- Destination country, only for EXPORTING stage
    notes               TEXT,                               -- Any extra notes recorded at this stage
    created_at          TEXT DEFAULT (datetime('now')),     -- Timestamp when this stage was recorded

    -- Foreign key constraint ensures every stage belongs to a valid gem
    FOREIGN KEY (gem_id) REFERENCES gems(gem_id)
        ON DELETE CASCADE   -- If a gem is deleted, all its stages are deleted too
        ON UPDATE CASCADE   -- If a gem_id changes, all its stages are updated too
);


-- ---------------------------------------------------------
-- Table: gem_alerts
-- ---------------------------------------------------------
-- This table stores fraud alert records generated by OriginVerifier.
-- When a gem's origin does not match known Sri Lankan mining locations,
-- an alert is saved here so it can be reviewed later.
-- Storing alerts separately keeps the main gems table clean.
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS gem_alerts (
    alert_id            INTEGER PRIMARY KEY AUTOINCREMENT,  -- Auto-generated alert ID
    gem_id              TEXT NOT NULL,                      -- The gem that triggered the alert
    alert_type          TEXT NOT NULL,                      -- e.g. ORIGIN_MISMATCH, MISSING_CERTIFICATE
    alert_message       TEXT NOT NULL,                      -- Human readable description of the alert
    is_resolved         INTEGER DEFAULT 0,                  -- 0 = unresolved, 1 = resolved
    created_at          TEXT DEFAULT (datetime('now')),     -- When the alert was created

    FOREIGN KEY (gem_id) REFERENCES gems(gem_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- ---------------------------------------------------------
-- Table: ceylon_mining_locations
-- ---------------------------------------------------------
-- This table stores the list of known legitimate Sri Lankan
-- gem mining locations used by OriginVerifier to validate
-- whether a gem truly originated in Sri Lanka.
-- Having this as a table instead of hardcoded values means
-- new mining areas can be added without changing Java code.
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS ceylon_mining_locations (
    location_id         INTEGER PRIMARY KEY AUTOINCREMENT,  -- Auto-generated ID
    district            TEXT NOT NULL,                      -- District name e.g. Ratnapura
    village             TEXT,                               -- Village or town near the mine
    mine_name           TEXT,                               -- Specific mine name if known
    is_active           INTEGER DEFAULT 1                   -- 1 = currently active mining area
);


-- ---------------------------------------------------------
-- Pre-populate known Ceylon mining locations
-- These are the verified Sri Lankan gem mining areas used
-- by OriginVerifier to authenticate gem origin claims.
-- INSERT OR IGNORE prevents duplicate rows on re-runs.
-- ---------------------------------------------------------

INSERT OR IGNORE INTO ceylon_mining_locations (district, village, mine_name)
VALUES
    ('Ratnapura',   'Pelmadulla',   'Pelmadulla Mine'),
    ('Ratnapura',   'Elapatha',     'Elapatha Gem Pit'),
    ('Ratnapura',   'Kuruwita',     'Kuruwita Mine'),
    ('Ratnapura',   'Ratnapura',    'Ratnapura City Mine'),
    ('Matale',      'Elahera',      'Elahera Mine'),
    ('Ampara',      'Okanda',       'Okanda Mine'),
    ('Badulla',     'Bibile',       'Bibile Mine'),
    ('Badulla',     'Okkampitiya',  'Okkampitiya Mine'),
    ('Kandy',       'Hasalaka',     'Hasalaka Mine'),
    ('Kalutara',    'Meetiyagoda',  'Meetiyagoda Mine');


-- ---------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------
-- Indexes are created on frequently searched columns to speed
-- up queries. Without indexes, every search would scan the
-- entire table row by row, which is slow for large datasets.
-- ---------------------------------------------------------

-- Index on gem_stages.gem_id to speed up loading a gem's full journey
CREATE INDEX IF NOT EXISTS idx_gem_stages_gem_id
    ON gem_stages(gem_id);

-- Index on gem_stages.stage_order to speed up ordering the chain
CREATE INDEX IF NOT EXISTS idx_gem_stages_order
    ON gem_stages(gem_id, stage_order);

-- Index on gems.gem_type to speed up searching gems by type
CREATE INDEX IF NOT EXISTS idx_gems_type
    ON gems(gem_type);

-- Index on gem_alerts.gem_id to speed up loading alerts for a gem
CREATE INDEX IF NOT EXISTS idx_alerts_gem_id
    ON gem_alerts(gem_id);

-- Index on gem_alerts.is_resolved to quickly find unresolved alerts
CREATE INDEX IF NOT EXISTS idx_alerts_resolved
    ON gem_alerts(is_resolved);